/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_set_util_FFmpegUtil */

#ifndef _Included_com_set_util_FFmpegUtil
#define _Included_com_set_util_FFmpegUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_set_util_FFmpegUtil
 * Method:    getInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_set_util_FFmpegUtil_getInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
