/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_set_util_JniUtils */

#ifndef _Included_com_set_util_JniUtils
#define _Included_com_set_util_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_set_util_JniUtils
 * Method:    getStringFormC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_set_util_JniUtils_getStringFormC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
